Hide mce tooltips
paulschreiber/liveblog pull request #19
Opened 2018-05-18 12:27 UTC by adamsilverstein

also, slight refactoring of mce startup

2018-05-18 19:01 UTC, paulschreiber requested changes
Please resolve the merge conflicts.

2018-05-18 20:16 UTC, adamsilverstein commented
@paulschreiber resolved merge conflicts

2018-05-18 20:42 UTC, paulschreiber commented on src/react/components/TinyMCEEditor.js
> +        editor..clearHeadline = this.props.clearHeadline;
should this have one `.`?

2018-05-22 18:18 UTC, adamsilverstein commented on src/react/components/TinyMCEEditor.js
> +        editor..clearHeadline = this.props.clearHeadline;
oops, no - will correct.

2018-05-22 18:22 UTC, adamsilverstein commented
@paulschreiber - corrected, the changes in that file were unrelated

2018-05-22 18:29 UTC, paulschreiber approved these changes

2018-05-22 18:30 UTC, paulschreiber requested changes

2018-05-22 18:30 UTC, paulschreiber commented on assets/dashboard/app.css
> +body.wp-admin.liveblog.post-type-fte_liveblog.wp-core-ui .mce-tooltip {
This hard-codes a reference to `fte_liveblog`, which won't work for others. Please use a different selector.

2018-05-23 13:24 UTC, adamsilverstein commented on assets/dashboard/app.css
> +body.wp-admin.liveblog.post-type-fte_liveblog.wp-core-ui .mce-tooltip {
Ok, to make this more generic i can rely on the body class that the plugin adds for live posts.

Question: what do you mean by "others" - other post types? are you using the liveblogging feature elsewhere or planning to?

2018-05-23 13:33 UTC, paulschreiber commented on assets/dashboard/app.css
> +body.wp-admin.liveblog.post-type-fte_liveblog.wp-core-ui .mce-tooltip {
Others: people not FiveThirtyEight who will also use this liveblog. (We want to merge these changes in to master, and not have a fork.)

2018-05-23 13:57 UTC, adamsilverstein commented on assets/dashboard/app.css
> +body.wp-admin.liveblog.post-type-fte_liveblog.wp-core-ui .mce-tooltip {
👍 I'll fix

2018-05-23 14:00 UTC, adamsilverstein commented on assets/dashboard/app.css
> +body.wp-admin.liveblog.post-type-fte_liveblog.wp-core-ui .mce-tooltip {
Fixed in https://github.com/paulschreiber/liveblog/pull/19/commits/7bbcc471b4d379ef315af7fc83a4a02480b7e3f1 where I removed all reverences to post-type-fte_liveblog in the css. the existing `.liveblog` targeting is specific enough.

2018-05-23 15:10 UTC, merged