Prevent update fail and alert on error
paulschreiber/liveblog pull request #36
Opened 2018-07-04 10:04 UTC by Ritesh-patel

- Disable Post Update button if there is no content in editor or content is too large
- On failed update, show error message and prevent editor from closing

2018-07-04 10:07 UTC, Ritesh-patel commented
@adamsilverstein can you take a look at this one? I have merged "Disable post update" and "Failure alerts" in single PR.

2018-07-05 16:05 UTC, adamsilverstein commented on src/react/components/TinyMCEEditor.js
> +      tinymce.activeEditor.setError(true, this.props.editorContainer.props.api.errorMessage);
`this.props.editorContainer.props.api.errorMessage` seems overly verbose, can you pass as props directly to the `TinyMCEEditor` component?

2018-07-05 16:05 UTC, adamsilverstein commented on src/react/components/TinyMCEEditor.js
> +    const thisError = this.props.editorContainer.props.api.error;
can you pass `this.props.editorContainer.props.api.error` directly as props to the `TinyMCEEditor` component?

2018-07-05 16:05 UTC, adamsilverstein commented on src/react/components/TinyMCEEditor.js
> +        tinymce.activeEditor.setPostingEnable = this.props.setPostingEnable;
lets clean up this and the three previous lines (and anything you need to get from props) with destructuring:

const {
clearAuthors,
clearHeadline,
setPostingEnable,
setError, 
} = this.props;

2018-07-05 16:05 UTC, adamsilverstein commented on src/react/components/TinyMCEEditor.js
> +        tinymce.activeEditor.setError(false, this.props.editorContainer.props.api.errorMessage);
replace `this.props.editorContainer.props.api.errorMessage` with props passed to component

2018-07-05 16:52 UTC, Ritesh-patel commented on src/react/components/TinyMCEEditor.js
> +        tinymce.activeEditor.setPostingEnable = this.props.setPostingEnable;
Understood but problem is we have same methods defined in upper scope https://github.com/Ritesh-patel/liveblog/blob/89fb6d67c39e05ac70225f4ef05aa3e792fa97be/src/react/components/TinyMCEEditor.js#L25, we can change names though but then we will need to change it into other places as well.
We can do something like this though
```
const editorMethods = {
          clearAuthors: this.props.clearAuthors,
          clearHeadline: this.props.clearHeadline,
          setPostingEnable: this.props.setPostingEnable,
          setError: this.props.setError,
};
tinymce.activeEditor = Object.assign(tinymce.activeEditor, editorMethods);
```

2018-07-05 17:20 UTC, Ritesh-patel commented on src/react/components/TinyMCEEditor.js
> +        tinymce.activeEditor.setPostingEnable = this.props.setPostingEnable;
No `Object.assign` doesn't work.

2018-07-05 20:45 UTC, adamsilverstein approved these changes
LGTM 👍

2018-07-06 11:13 UTC, Ritesh-patel commented
@paulschreiber this is ready now.

2018-07-18 18:10 UTC, paulschreiber requested changes

2018-07-18 18:10 UTC, paulschreiber commented on src/react/Editor/Editor.js
> +      setPostingEnable,
Should this be `setPostingEnabled`?

2018-07-18 18:10 UTC, paulschreiber commented on src/react/components/TinyMCEEditor.js
> +    const postingEnabled = content.length > 0 && content.length < 65535;
Put 65535 in a constant.

2018-07-18 18:10 UTC, paulschreiber commented on src/react/components/TinyMCEEditor.js
> +        tinymce.activeEditor.setPostingEnable = this.props.setPostingEnable;
@adamsilverstein is this ok?

2018-07-23 16:14 UTC, Ritesh-patel commented on src/react/Editor/Editor.js
> +      setPostingEnable,
It's a function which can take true/false value.`setPostingEnabled` is more like for setting a flag.

2018-07-23 17:26 UTC, paulschreiber commented on src/react/Editor/Editor.js
> +      setPostingEnable,
This is ungrammatical in its current form. You could go with setEnablePosting if Enable is to be treated as a verb.

2018-07-23 18:32 UTC, Ritesh-patel commented on src/react/Editor/Editor.js
> +      setPostingEnable,
Agreed, setEnablePosting sounds better.

2018-07-23 19:07 UTC, paulschreiber approved these changes

2018-07-23 19:08 UTC, merged